# Generated by Django 5.0.6 on 2024-06-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_complaint_image_alter_complaint_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Traffic Violation', 'Traffic Violation'), ('Delayed Services', 'Delayed Services'), ('Service Quality', 'Service Quality'), ('Service Denial', 'Service Denial'), ('Missuse of Funds', 'Missuse of Funds'), ('Road and Transportation Issues', 'Road and Transportation Issues'), ('Healthcare Services', 'Healthcare Services'), ('Misconduct Allegations', 'Misconduct Allegations'), ('Abuse of Power', 'Abuse of Power'), ('Other', 'Other')], max_length=100),
        ),
    ]
